"""add labels and issue labels

Revision ID: 1e04a2367fd8
Revises: f513963243a6
Create Date: 2026-03-11 17:14:21.132308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e04a2367fd8'
down_revision: Union[str, Sequence[str], None] = 'f513963243a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_label_project_name')
    )
    op.create_index(op.f('ix_labels_id'), 'labels', ['id'], unique=False)
    op.create_index(op.f('ix_labels_project_id'), 'labels', ['project_id'], unique=False)
    op.create_table('issue_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'label_id', name='uq_issue_label_issue_label')
    )
    op.create_index(op.f('ix_issue_labels_id'), 'issue_labels', ['id'], unique=False)
    op.create_index(op.f('ix_issue_labels_issue_id'), 'issue_labels', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issue_labels_label_id'), 'issue_labels', ['label_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_labels_label_id'), table_name='issue_labels')
    op.drop_index(op.f('ix_issue_labels_issue_id'), table_name='issue_labels')
    op.drop_index(op.f('ix_issue_labels_id'), table_name='issue_labels')
    op.drop_table('issue_labels')
    op.drop_index(op.f('ix_labels_project_id'), table_name='labels')
    op.drop_index(op.f('ix_labels_id'), table_name='labels')
    op.drop_table('labels')
    # ### end Alembic commands ###
